In [2]:
print("hello")

hello


In [3]:
import numpy as np

In [4]:
np.set_printoptions(suppress=True) #cleaner printing (no scientific notation)


1.Scalar,Vector,Matrix & Tensor in Numpy

In [5]:
#scalar
scalar = 5.0
print(scalar)
print(type(scalar))

#vector
vector = np.array(
    [3,7,2]
)
print("vector: ")
print(vector)
print("shape of vector:", vector.shape)

#matrix - 2D data
matrix = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print("matrix:")
print(matrix)
print("shape of matrix:", matrix.shape)

#tensor - 3D data
tensor = np.array(
    [ 
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [11,12,13],
            [14,15,16]
        ]
       
    ]
)
print("tensor:")
print(tensor)
print("shape of matrix:", tensor.shape)





5.0
<class 'float'>
vector: 
[3 7 2]
shape of vector: (3,)
matrix:
[[1 2 3]
 [4 5 6]]
shape of matrix: (2, 3)
tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
shape of matrix: (2, 2, 3)


2.Creating vectors and matrices for ml style data

In [7]:
#imagine we have 3 samples and 2 features
#feature 1: hours studied
#feature 2:number of practice questions
#target: pass(1) or fail(0)

X= np.array(
    [
    [2,30],
    [5,80],
    [1,20]
    ]
)
y = np.array([0,1,0])

print("Input Data matrix X:\n",X)
print("X shape: ", X.shape)

print("Input Data matrix y:\n",y)
print("y shape: ", y.shape)

#A single sample as a vector
x1 = X[0] #first row
print("\n First sample as a vector:", x1)
print("x1 shape: ",x1.shape)

Input Data matrix X:
 [[ 2 30]
 [ 5 80]
 [ 1 20]]
X shape:  (3, 2)
Input Data matrix y:
 [0 1 0]
y shape:  (3,)

 First sample as a vector: [ 2 30]
x1 shape:  (2,)


3.Basic operations: addition, scalar multiplication, transpose

In [13]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("v1:", v1)
print("v2:", v2)

#vector addition
v_add = v1+v2
print("\n vector addition v1+v2: ", v_add)

#scalar multiplication
v1_scaled = 2 * v1
print("\n scalar multiplication 2*v1: ", v1_scaled)
#matrix example
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [10,20],
    [30,40]
])
print("\n matrix A :\n", A)
print("Matrix B:\n", B)
#matrix additon 
A_add_B = A+B
print("\n matrix addition A + B:\n", A_add_B)

#scalar multiplication
A_scaled = 0.5*A
print("Scalar multiplication 0.5*A:\n", A_scaled)

#transpose
A_T = A.T
print("\n transpose of A: \n", A_T)
print("A shape: ", A.shape, "A.T shape:", A_T.shape)


v1: [1 2 3]
v2: [4 5 6]

 vector addition v1+v2:  [5 7 9]

 scalar multiplication 2*v1:  [2 4 6]

 matrix A :
 [[1 2]
 [3 4]]
Matrix B:
 [[10 20]
 [30 40]]

 matrix addition A + B:
 [[11 22]
 [33 44]]
Scalar multiplication 0.5*A:
 [[0.5 1. ]
 [1.5 2. ]]

 transpose of A: 
 [[1 3]
 [2 4]]
A shape:  (2, 2) A.T shape: (2, 2)
