In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

DOT Product

In [3]:
v1 = np.array([1,3])
v2 = np.array([4,2])
print("v1:", v1)
print("v2:", v2)

v1: [1 3]
v2: [4 2]


In [5]:
dot = np.dot(v1, v2)
print(("Dot product v1.v2:", dot))

('Dot product v1.v2:', np.int64(10))


In [6]:
print(dot)

10


Euclidean distance

In [7]:
diff = v1-v2
print("difference v1-v2:",diff)

difference v1-v2: [-3  1]


In [9]:
distance = np.linalg.norm(diff) #use linalg.norm instead writing whole distancce formula

print("euclidean distance b/w v1 and v2:", distance)

euclidean distance b/w v1 and v2: 3.1622776601683795


Matrix multiplication and Linear Model

In [10]:
X = np.array(
    [
        [1.0, 30.0],
        [2.0, 50.0],
        [3.0, 70.0]
    ]
)
print("X:\n", X)
print("X shape:", X.shape)

X:
 [[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]
X shape: (3, 2)


In [11]:
w = np.array([
    [0.5],
    [0.1]
])
print("\nw:\n", w)
print("w shape:", w.shape)


w:
 [[0.5]
 [0.1]]
w shape: (2, 1)


In [15]:
Xw = X @ w #dot
print("Xw:")
print(Xw)
print("Xw.shape:",Xw.shape)

Xw:
[[3.5]
 [6. ]
 [8.5]]
Xw.shape: (3, 1)


y=Xw+b

In [16]:
b=2.0
print("\nBias b:", b)



Bias b: 2.0


In [18]:
y = Xw + b
print("\nPredictions y = Xw + b:\n",y)
print("y shape:",y.shape)


Predictions y = Xw + b:
 [[ 5.5]
 [ 8. ]
 [10.5]]
y shape: (3, 1)


In [19]:
print(X)

[[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]


In [20]:
print(w)

[[0.5]
 [0.1]]


In [21]:
print(b)

2.0


In [22]:
print(y)

[[ 5.5]
 [ 8. ]
 [10.5]]


Connecting this to a sample dataset

In [23]:
data = np.array([
    [86, 26.6, 31, 0],
    [183, 23.3, 32, 1],
    [89, 28.1, 21, 0],
    [137, 43.1, 33, 1],
])
print("full data matrix:\n", data)
print("data shape:", data.shape)

full data matrix:
 [[ 86.   26.6  31.    0. ]
 [183.   23.3  32.    1. ]
 [ 89.   28.1  21.    0. ]
 [137.   43.1  33.    1. ]]
data shape: (4, 4)


In [ ]:
x_features = data[:, :-1] #all cols except last col
y_target = data[:, -1] #only last col
print("\nFeature matrix X:\n", x_features)
print("X shape: ", x_features.shape)

print("\nTarget vector y:\n", y_target)
print("y shape: ", y_target.shape)



Feature matrix X:
 [[ 86.   26.6  31. ]
 [183.   23.3  32. ]
 [ 89.   28.1  21. ]
 [137.   43.1  33. ]]
X shape:  (4, 3)

Target vector y:
 [0. 1. 0. 1.]
y shape:  (4,)
